//HintName: Solution.g.cs
// <auto-generated/>

using Fallout.Application.Solutions;
using Fallout.Kernel.IO;
using System.Runtime.CompilerServices;

internal class Solution(AbsolutePath path, object handle) : Fallout.Application.Solutions.Solution(path, handle)
{
    public Fallout.Application.Solutions.Project _build => this.GetProject("_build");
    public Fallout.Application.Solutions.Project Fallout_Application => this.GetProject("Fallout.Application");
    public Fallout.Application.Solutions.Project Fallout_Application_Components => this.GetProject("Fallout.Application.Components");
    public Fallout.Application.Solutions.Project Fallout_Architecture_Tests => this.GetProject("Fallout.Architecture.Tests");
    public Fallout.Application.Solutions.Project Fallout_Build_Shared => this.GetProject("Fallout.Build.Shared");
    public Fallout.Application.Solutions.Project Fallout_Build_Tests => this.GetProject("Fallout.Build.Tests");
    public Fallout.Application.Solutions.Project Fallout_Cli => this.GetProject("Fallout.Cli");
    public Fallout.Application.Solutions.Project Fallout_Cli_Tests => this.GetProject("Fallout.Cli.Tests");
    public Fallout.Application.Solutions.Project Fallout_Common => this.GetProject("Fallout.Common");
    public Fallout.Application.Solutions.Project Fallout_Common_Tests => this.GetProject("Fallout.Common.Tests");
    public Fallout.Application.Solutions.Project Fallout_Components_Tests => this.GetProject("Fallout.Components.Tests");
    public Fallout.Application.Solutions.Project Fallout_Consumer_Local => this.GetProject("Fallout.Consumer.Local");
    public Fallout.Application.Solutions.Project Fallout_Consumer_NuGet => this.GetProject("Fallout.Consumer.NuGet");
    public Fallout.Application.Solutions.Project Fallout_Domain => this.GetProject("Fallout.Domain");
    public Fallout.Application.Solutions.Project Fallout_Domain_Tests => this.GetProject("Fallout.Domain.Tests");
    public Fallout.Application.Solutions.Project Fallout_Infrastructure_ProjectModel => this.GetProject("Fallout.Infrastructure.ProjectModel");
    public Fallout.Application.Solutions.Project Fallout_Kernel => this.GetProject("Fallout.Kernel");
    public Fallout.Application.Solutions.Project Fallout_Kernel_IO_Compression => this.GetProject("Fallout.Kernel.IO.Compression");
    public Fallout.Application.Solutions.Project Fallout_Kernel_IO_Globbing => this.GetProject("Fallout.Kernel.IO.Globbing");
    public Fallout.Application.Solutions.Project Fallout_Kernel_Net => this.GetProject("Fallout.Kernel.Net");
    public Fallout.Application.Solutions.Project Fallout_Kernel_Text_Json => this.GetProject("Fallout.Kernel.Text.Json");
    public Fallout.Application.Solutions.Project Fallout_Kernel_Text_Yaml => this.GetProject("Fallout.Kernel.Text.Yaml");
    public Fallout.Application.Solutions.Project Fallout_Migrate => this.GetProject("Fallout.Migrate");
    public Fallout.Application.Solutions.Project Fallout_Migrate_Analyzers => this.GetProject("Fallout.Migrate.Analyzers");
    public Fallout.Application.Solutions.Project Fallout_Migrate_Analyzers_Tests => this.GetProject("Fallout.Migrate.Analyzers.Tests");
    public Fallout.Application.Solutions.Project Fallout_Migrate_Tests => this.GetProject("Fallout.Migrate.Tests");
    public Fallout.Application.Solutions.Project Fallout_MSBuildTasks => this.GetProject("Fallout.MSBuildTasks");
    public Fallout.Application.Solutions.Project Fallout_Persistence_Solution => this.GetProject("Fallout.Persistence.Solution");
    public Fallout.Application.Solutions.Project Fallout_Persistence_Solution_Benchmarks => this.GetProject("Fallout.Persistence.Solution.Benchmarks");
    public Fallout.Application.Solutions.Project Fallout_ProjectModel_Tests => this.GetProject("Fallout.ProjectModel.Tests");
    public Fallout.Application.Solutions.Project Fallout_Solution => this.GetProject("Fallout.Solution");
    public Fallout.Application.Solutions.Project Fallout_Solution_Tests => this.GetProject("Fallout.Solution.Tests");
    public Fallout.Application.Solutions.Project Fallout_SourceGenerators => this.GetProject("Fallout.SourceGenerators");
    public Fallout.Application.Solutions.Project Fallout_SourceGenerators_Tests => this.GetProject("Fallout.SourceGenerators.Tests");
    public Fallout.Application.Solutions.Project Fallout_Tooling => this.GetProject("Fallout.Tooling");
    public Fallout.Application.Solutions.Project Fallout_Tooling_Generator => this.GetProject("Fallout.Tooling.Generator");
    public Fallout.Application.Solutions.Project Fallout_Tooling_Tests => this.GetProject("Fallout.Tooling.Tests");
    public Fallout.Application.Solutions.Project Fallout_Utilities_Tests => this.GetProject("Fallout.Utilities.Tests");
    public Fallout.Application.Solutions.Project Nuke_Build => this.GetProject("Nuke.Build");
    public Fallout.Application.Solutions.Project Nuke_Common => this.GetProject("Nuke.Common");
    public Fallout.Application.Solutions.Project Nuke_Components => this.GetProject("Nuke.Components");
    public Fallout.Application.Solutions.Project Nuke_Components_Shim_Tests => this.GetProject("Nuke.Components.Shim.Tests");

    public _misc misc => Unsafe.As<_misc>(this.GetSolutionFolder("misc"));

    internal class _misc : Fallout.Application.Solutions.SolutionFolder
    {
    
    
    }
}