//HintName: global__Fallout.Application.WithNested.g.cs
// <auto-generated/>
// Generated by Fallout.SourceGenerators.TransitionShimGenerator.
// Mirrors a canonical Fallout.* type as a transition shim.

namespace Nuke.Common
{
    public partial class WithNested : global::Fallout.Application.WithNested
    {
        public WithNested() { }

        public new partial class Nested : global::Fallout.Application.WithNested.Nested
        {
            public Nested() { }
        }
    }
}
