//HintName: global__Fallout.Application.Abstr.g.cs
// <auto-generated/>
// Generated by Fallout.SourceGenerators.TransitionShimGenerator.
// Mirrors a canonical Fallout.* type as a transition shim.

namespace Nuke.Common
{
    public abstract partial class Abstr : global::Fallout.Application.Abstr
    {
        protected Abstr() { }
    }
}
