//HintName: global__Fallout.Application.StaticHelpers.g.cs
// <auto-generated/>
// Generated by Fallout.SourceGenerators.TransitionShimGenerator.
// Mirrors a canonical Fallout.* type as a transition shim.

namespace Nuke.Common
{
    public static partial class StaticHelpers
    {
        public static int Plain(int a) => global::Fallout.Application.StaticHelpers.Plain(a);
        public static void VoidReturn(string s) => global::Fallout.Application.StaticHelpers.VoidReturn(s);
        public static T Generic<T>(T input) where T : class => global::Fallout.Application.StaticHelpers.Generic<T>(input);
        public static int WithOptional(int a, int b = 7, string s = "hello") => global::Fallout.Application.StaticHelpers.WithOptional(a, b, s);
        public static int Sum(params int[] nums) => global::Fallout.Application.StaticHelpers.Sum(nums);
        public static int TryParse(string s, out int value) => global::Fallout.Application.StaticHelpers.TryParse(s, out value);
        public static string AsHex(this byte b) => global::Fallout.Application.StaticHelpers.AsHex(b);
    }
}
