//HintName: global__Fallout.Application.Generic_T_.g.cs
// <auto-generated/>
// Generated by Fallout.SourceGenerators.TransitionShimGenerator.
// Mirrors a canonical Fallout.* type as a transition shim.

namespace Nuke.Common
{
    public partial class Generic<T> : global::Fallout.Application.Generic<T>
        where T : class
    {
        public Generic(T item) : base(item) { }
    }
}
