//HintName: global__Fallout.Application.MyAttr.g.cs
// <auto-generated/>
// Generated by Fallout.SourceGenerators.TransitionShimGenerator.
// Mirrors a canonical Fallout.* type as a transition shim.

namespace Nuke.Common
{
    public partial class MyAttr : global::Fallout.Application.MyAttr
    {
        public MyAttr(int n) : base(n) { }
    }
}
