using System;

namespace Fallout.Architecture.Tests;

/// <summary>
/// The debt register. Each array is the set of <b>known, pre-existing</b> violations a single fitness rule is
/// allowed to have today — keyed by offending type full name. <see cref="Ratchet"/> fails the test if a rule
/// gains a violation not listed here (a regression) or if a listed entry stops violating (improvement to lock
/// in). The lists may only shrink over time; an empty list means a strict, zero-tolerance invariant.
///
/// When a rule legitimately reports a new violation, do not reflexively add it here — first decide whether the
/// dependency is wrong (fix the code) or intended (add it with a one-line justification). This file is the
/// honest record of where Fallout's architecture does not yet match its intended shape.
///
/// To regenerate after the architecture changes, see docs/architecture-tests.md.
/// </summary>
internal static class KnownViolations
{
    /// <summary>For invariants that already hold — zero tolerance.</summary>
    public static readonly string[] None = Array.Empty<string>();

    /// <summary>
    /// Namespace ↔ assembly drift: types whose namespace is not rooted at their assembly name. This is the
    /// legacy NUKE namespace sprawl — chiefly the <c>Fallout.Common.*</c> namespace spanning the Build / Common /
    /// Tooling assemblies, plus the <c>Fallout.Utilities.*</c> satellites still emitting <c>Fallout.Common.*</c>
    /// types and the <c>Fallout.Solutions.*</c> facade types. It shrinks as the onion-architecture refactor
    /// (ADR-0006, on refactor/architecture) renames things; each removed entry is a permanent gain the ratchet
    /// locks in. Generated, off-by-default at <see cref="Ratchet.Enforce"/> time.
    /// </summary>
    public static readonly string[] NamespaceAssemblyDrift =
    [
        "Fallout.Common.ArgumentParser",
        "Fallout.Common.Assert",
        "Fallout.Common.AsyncHelper",
        "Fallout.Common.CI.BuildServerConfigurationGeneration",
        "Fallout.Common.CI.BuildServerConfigurationGenerationAttributeBase",
        "Fallout.Common.CI.CIAttribute",
        "Fallout.Common.CI.ChainedConfigurationAttributeBase",
        "Fallout.Common.CI.ConfigurationAttributeBase",
        "Fallout.Common.CI.ConfigurationEntity",
        "Fallout.Common.CI.GenerateBuildServerConfigurationsAttribute",
        "Fallout.Common.CI.IBuildServer",
        "Fallout.Common.CI.IConfigurationGenerator",
        "Fallout.Common.CI.InvokeBuildServerConfigurationGenerationAttribute",
        "Fallout.Common.CI.NoConvertAttribute",
        "Fallout.Common.CI.Partition",
        "Fallout.Common.CI.Partition+TypeConverter",
        "Fallout.Common.CI.PartitionAttribute",
        "Fallout.Common.CI.SerializeBuildServerStateAttribute",
        "Fallout.Common.CI.ShutdownDotNetAfterServerBuildAttribute",
        "Fallout.Common.Cleanup",
        "Fallout.Common.Constants",
        "Fallout.Common.ControlFlow",
        "Fallout.Common.DefaultOutput",
        "Fallout.Common.DependencyBehavior",
        "Fallout.Common.DisableDefaultOutputAttribute",
        "Fallout.Common.EnvironmentInfo",
        "Fallout.Common.ExecutableTargetExtensions",
        "Fallout.Common.Execution.ArgumentsFromGitCommitMessageAttribute",
        "Fallout.Common.Execution.ArgumentsFromParametersFileAttribute",
        "Fallout.Common.Execution.BuildExecutor",
        "Fallout.Common.Execution.BuildExtensionAttributeBase",
        "Fallout.Common.Execution.BuildManager",
        "Fallout.Common.Execution.DelegateRequirementService",
        "Fallout.Common.Execution.EventInvoker",
        "Fallout.Common.Execution.ExecutableTarget",
        "Fallout.Common.Execution.ExecutableTargetFactory",
        "Fallout.Common.Execution.ExecutionPlanner",
        "Fallout.Common.Execution.ExecutionStatus",
        "Fallout.Common.Execution.HandleHelpRequestsAttribute",
        "Fallout.Common.Execution.HandleReSharperSurrogateArgumentsAttribute",
        "Fallout.Common.Execution.HandleShellCompletionAttribute",
        "Fallout.Common.Execution.HandleVisualStudioDebuggingAttribute",
        "Fallout.Common.Execution.IBuildExtension",
        "Fallout.Common.Execution.IOnBuildCreated",
        "Fallout.Common.Execution.IOnBuildFinished",
        "Fallout.Common.Execution.IOnBuildInitialized",
        "Fallout.Common.Execution.IOnTargetFailed",
        "Fallout.Common.Execution.IOnTargetRunning",
        "Fallout.Common.Execution.IOnTargetSkipped",
        "Fallout.Common.Execution.IOnTargetSucceeded",
        "Fallout.Common.Execution.IOnTargetSummaryUpdated",
        "Fallout.Common.Execution.ITargetModel",
        "Fallout.Common.Execution.Logging",
        "Fallout.Common.Execution.Logging+ExecutingTargetLogEventEnricher",
        "Fallout.Common.Execution.Logging+InMemorySink",
        "Fallout.Common.Execution.Rider",
        "Fallout.Common.Execution.SchemaUtility",
        "Fallout.Common.Execution.SchemaUtility+SchemaContext",
        "Fallout.Common.Execution.TargetDefinition",
        "Fallout.Common.Execution.TargetExecutionException",
        "Fallout.Common.Execution.Telemetry",
        "Fallout.Common.Execution.TelemetryAttribute",
        "Fallout.Common.Execution.Terminal",
        "Fallout.Common.Execution.Theming.AnsiConsoleHostTheme",
        "Fallout.Common.Execution.Theming.IHostTheme",
        "Fallout.Common.Execution.Theming.SystemConsoleHostTheme",
        "Fallout.Common.Execution.ToolRequirementService",
        "Fallout.Common.Execution.UnsetVisualStudioEnvironmentVariablesAttribute",
        "Fallout.Common.Execution.UpdateNotificationAttribute",
        "Fallout.Common.Execution.VSCode",
        "Fallout.Common.Execution.VisualStudio",
        "Fallout.Common.FalloutBuild",
        "Fallout.Common.Git.GitProtocol",
        "Fallout.Common.Git.GitRepository",
        "Fallout.Common.Git.GitRepositoryExtensions",
        "Fallout.Common.Host",
        "Fallout.Common.Host+LogEventSink",
        "Fallout.Common.Host+TypeConverter",
        "Fallout.Common.IFalloutBuild",
        "Fallout.Common.IO.AbsolutePath",
        "Fallout.Common.IO.AbsolutePath+TypeConverter",
        "Fallout.Common.IO.AbsolutePathExtensions",
        "Fallout.Common.IO.CompressionExtensions",
        "Fallout.Common.IO.ExistsPolicy",
        "Fallout.Common.IO.Globbing",
        "Fallout.Common.IO.GlobbingCaseSensitivity",
        "Fallout.Common.IO.IAbsolutePathHolder",
        "Fallout.Common.IO.PathConstruction",
        "Fallout.Common.IO.RelativePath",
        "Fallout.Common.IO.UnixRelativePath",
        "Fallout.Common.IO.WinRelativePath",
        "Fallout.Common.ITargetDefinition",
        "Fallout.Common.LegacyEnvironment",
        "Fallout.Common.LogLevel",
        "Fallout.Common.OnDemandAttribute",
        "Fallout.Common.OnDemandValueInjectionAttribute",
        "Fallout.Common.OptionalAttribute",
        "Fallout.Common.ParameterAttribute",
        "Fallout.Common.ParameterPrefixAttribute",
        "Fallout.Common.ParameterService",
        "Fallout.Common.PlatformFamily",
        "Fallout.Common.RequiredAttribute",
        "Fallout.Common.RequiresAttribute",
        "Fallout.Common.RequiresAttribute`1",
        "Fallout.Common.SecretAttribute",
        "Fallout.Common.Setup",
        "Fallout.Common.SpecialFolders",
        "Fallout.Common.Target",
        "Fallout.Common.Tooling.AptGetPackageRequirement",
        "Fallout.Common.Tooling.AptGetToolAttribute",
        "Fallout.Common.Tooling.ArgumentAttribute",
        "Fallout.Common.Tooling.ArgumentEscapeAttribute",
        "Fallout.Common.Tooling.ArgumentStringHandler",
        "Fallout.Common.Tooling.BuilderAttribute",
        "Fallout.Common.Tooling.CombinatorialConfigure`1",
        "Fallout.Common.Tooling.CommandAttribute",
        "Fallout.Common.Tooling.ConfigureExtensions",
        "Fallout.Common.Tooling.Configure`1",
        "Fallout.Common.Tooling.Configure`2",
        "Fallout.Common.Tooling.DefaultLogLevel",
        "Fallout.Common.Tooling.DelegateHelper",
        "Fallout.Common.Tooling.EnumValueAttribute",
        "Fallout.Common.Tooling.Enumeration",
        "Fallout.Common.Tooling.Enumeration+TypeConverter`1",
        "Fallout.Common.Tooling.EnumerationExtensions",
        "Fallout.Common.Tooling.EnumerationJsonConverterFactory",
        "Fallout.Common.Tooling.EnumerationJsonConverterFactory+TypedConverter`1",
        "Fallout.Common.Tooling.IOptions",
        "Fallout.Common.Tooling.IProcess",
        "Fallout.Common.Tooling.IRequireAptGetPackage",
        "Fallout.Common.Tooling.IRequireNpmPackage",
        "Fallout.Common.Tooling.IRequireNuGetPackage",
        "Fallout.Common.Tooling.IRequirePathTool",
        "Fallout.Common.Tooling.IRequireTool",
        "Fallout.Common.Tooling.IRequireToolWithVersion",
        "Fallout.Common.Tooling.IToolOptionsWithFramework",
        "Fallout.Common.Tooling.LogErrorAsStandard",
        "Fallout.Common.Tooling.LogLevelPattern",
        "Fallout.Common.Tooling.NpmPackageRequirement",
        "Fallout.Common.Tooling.NpmToolAttribute",
        "Fallout.Common.Tooling.NpmToolPathResolver",
        "Fallout.Common.Tooling.NpmVersionResolver",
        "Fallout.Common.Tooling.NuGetPackageRequirement",
        "Fallout.Common.Tooling.NuGetPackageResolver",
        "Fallout.Common.Tooling.NuGetPackageResolver+InstalledPackage",
        "Fallout.Common.Tooling.NuGetPackageResolver+InstalledPackage+Comparer",
        "Fallout.Common.Tooling.NuGetToolAttribute",
        "Fallout.Common.Tooling.NuGetToolPathResolver",
        "Fallout.Common.Tooling.NuGetVersionResolver",
        "Fallout.Common.Tooling.ObjectFromFieldConverter",
        "Fallout.Common.Tooling.ObjectFromFieldConverter+TypedConverter`1",
        "Fallout.Common.Tooling.Options",
        "Fallout.Common.Tooling.Options+TypeConverter",
        "Fallout.Common.Tooling.Options+TypeConverter+InnerConverter`1",
        "Fallout.Common.Tooling.OptionsExtensions",
        "Fallout.Common.Tooling.Output",
        "Fallout.Common.Tooling.OutputType",
        "Fallout.Common.Tooling.PaketPackageResolver",
        "Fallout.Common.Tooling.PathToolAttribute",
        "Fallout.Common.Tooling.PathToolRequirement",
        "Fallout.Common.Tooling.Process2",
        "Fallout.Common.Tooling.ProcessException",
        "Fallout.Common.Tooling.ProcessExtensions",
        "Fallout.Common.Tooling.ProcessTasks",
        "Fallout.Common.Tooling.Tool",
        "Fallout.Common.Tooling.ToolAttribute",
        "Fallout.Common.Tooling.ToolExecutor",
        "Fallout.Common.Tooling.ToolInjectionAttributeBase",
        "Fallout.Common.Tooling.ToolOptions",
        "Fallout.Common.Tooling.ToolOptionsExtensions",
        "Fallout.Common.Tooling.ToolOptionsWithFrameworkExtensions",
        "Fallout.Common.Tooling.ToolPathResolver",
        "Fallout.Common.Tooling.ToolRequirement",
        "Fallout.Common.Tooling.ToolResolver",
        "Fallout.Common.Tooling.ToolTasks",
        "Fallout.Common.Tooling.ToolingExtensions",
        "Fallout.Common.Tooling.VerbosityMapping",
        "Fallout.Common.Tooling.VerbosityMappingAttribute",
        "Fallout.Common.Utilities.AssemblyExtensions",
        "Fallout.Common.Utilities.Collections.ArrayExtensions",
        "Fallout.Common.Utilities.Collections.DictionaryExtensions",
        "Fallout.Common.Utilities.Collections.EnumerableExtensions",
        "Fallout.Common.Utilities.Collections.EnumerableExtensions+DelegateEqualityComparer`2",
        "Fallout.Common.Utilities.Collections.LookupExtensions",
        "Fallout.Common.Utilities.Collections.LookupTable`2",
        "Fallout.Common.Utilities.CompletionUtility",
        "Fallout.Common.Utilities.ConsoleUtility",
        "Fallout.Common.Utilities.CredentialStore",
        "Fallout.Common.Utilities.CustomFileWriter",
        "Fallout.Common.Utilities.DelegateDisposable",
        "Fallout.Common.Utilities.DisposableExtensions",
        "Fallout.Common.Utilities.EncryptionUtility",
        "Fallout.Common.Utilities.ExceptionExtensions",
        "Fallout.Common.Utilities.JsonExtensions",
        "Fallout.Common.Utilities.JsonNodeExtensions",
        "Fallout.Common.Utilities.Lazy",
        "Fallout.Common.Utilities.Net.HttpClientExtensions",
        "Fallout.Common.Utilities.Net.HttpRequestBuilder",
        "Fallout.Common.Utilities.Net.HttpRequestExtensions",
        "Fallout.Common.Utilities.Net.HttpResponseException",
        "Fallout.Common.Utilities.Net.HttpResponseExtensions",
        "Fallout.Common.Utilities.Net.HttpResponseInspector",
        "Fallout.Common.Utilities.ObjectExtensions",
        "Fallout.Common.Utilities.ReflectionUtility",
        "Fallout.Common.Utilities.ResourceUtility",
        "Fallout.Common.Utilities.StringExtensions",
        "Fallout.Common.Utilities.TaskExtensions",
        "Fallout.Common.Utilities.UrlExtensions",
        "Fallout.Common.Utilities.XElementExtensions",
        "Fallout.Common.Utilities.XNodeExtensions",
        "Fallout.Common.Utilities.XmlExtensions",
        "Fallout.Common.ValueInjection.InjectNonParameterValuesAttribute",
        "Fallout.Common.ValueInjection.InjectParameterValuesAttribute",
        "Fallout.Common.ValueInjection.ValueInjectionAttributeBase",
        "Fallout.Common.ValueInjection.ValueInjectionUtility",
        "Fallout.Common.Verbosity",
        "Fallout.Migrate.Shims.ShimAllPublicTypesUnderAttribute",
        "Fallout.Solutions.ProjectExtensions",
        "Fallout.Solutions.ProjectModelTasks",
        "Fallout.Solutions.SolutionAttribute",
    ];
}
